const seedBooks=[
 {id:1,title:'Atomic Habits',author:'James Clear',cat:'Personal Growth',status:'Available',shelf:'PG-01',copies:4,available:4,resource:'Book'},
 {id:2,title:'The River Between',author:'Ngũgĩ wa Thiong’o',cat:'Fiction',status:'Available',shelf:'F-04',copies:5,available:5,resource:'Book'},
 {id:3,title:'Advanced Mathematics',author:'Academic Collection',cat:'Academic',status:'Borrowed',shelf:'M-03',copies:8,available:5,resource:'Textbook'},
 {id:4,title:'Biology for Secondary Schools',author:'Science Collection',cat:'Academic',status:'Available',shelf:'B-03',copies:12,available:9,resource:'Textbook'},
 {id:5,title:'The Digital World',author:'Technology Collection',cat:'Technology',status:'Available',shelf:'T-02',copies:6,available:6,resource:'Book'},
 {id:6,title:'Stories for Young Readers',author:'AMG Children’s Shelf',cat:'Children',status:'Available',shelf:'C-01',copies:10,available:10,resource:'Book'},
 {id:7,title:'Think and Grow Rich',author:'Napoleon Hill',cat:'Personal Growth',status:'Available',shelf:'PG-04',copies:3,available:3,resource:'Book'},
 {id:8,title:'KCSE Revision Companion',author:'AMG Learning Centre',cat:'Academic',status:'Borrowed',shelf:'R-01',copies:10,available:7,resource:'Revision'}
];
const getBooks=()=>JSON.parse(localStorage.getItem('amg-books')||'null')||seedBooks;
const saveBooks=b=>localStorage.setItem('amg-books',JSON.stringify(b));
let books=getBooks(),current='All';
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function showModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false')}
function closeModal(){$('#modal').classList.remove('open');$('#modal').setAttribute('aria-hidden','true')}
function render(query=''){books=getBooks();const q=query.toLowerCase();const list=books.filter(b=>(current==='All'||b.cat===current)&&(!q||`${b.title} ${b.author} ${b.cat} ${b.resource}`.toLowerCase().includes(q)));$('#bookGrid').innerHTML=list.map((b,i)=>`<article class="book-card"><div class="book-art" style="background:linear-gradient(145deg,hsl(${145+i*28} 30% 32%),#17352e)"><h3>${b.title}</h3></div><div class="book-meta"><strong>${b.title}</strong><span>by ${b.author} · ${b.shelf}</span><div class="book-bottom"><span class="status ${b.status==='Borrowed'?'borrowed':''}">${b.status}</span><button class="text-btn" data-book="${b.id}">Details →</button></div></div></article>`).join('');$('#emptyBooks').hidden=list.length>0;$$('[data-book]').forEach(x=>x.onclick=()=>showBook(Number(x.dataset.book)));updateStats()}
function updateStats(){const borrowed=books.filter(b=>b.status==='Borrowed').length;const total=books.reduce((n,b)=>n+b.copies,0);$('#statBooks').textContent=total+'+';$('#statBorrowed').textContent=borrowed;$('#statLearners').textContent='327';$('#statOverdue').textContent='12'}
function showBook(id){const b=books.find(x=>x.id===id)||books[0];showModal(`<div class="portal-head"><div><span class="eyebrow">LIBRARY RECORD</span><h2>${b.title}</h2></div><span class="status ${b.status==='Borrowed'?'borrowed':''}">${b.status}</span></div><div class="portal-grid"><div class="portal-card"><h4>Author</h4><p>${b.author}</p></div><div class="portal-card"><h4>Category</h4><p>${b.cat}</p></div><div class="portal-card"><h4>Location</h4><p>Shelf ${b.shelf}</p></div><div class="portal-card"><h4>Copies</h4><p>${b.available} available of ${b.copies}</p></div></div><p>${b.resource} · Searchable catalogue record · QR-ready.</p><button class="btn btn-primary" onclick="reserveBook(${b.id})">${b.status==='Available'?'Reserve / request book':'Join waitlist'}</button>`)}
function reserveBook(id){const b=books.find(x=>x.id===id);alert(`${b.title} has been added to your reservation request. A librarian will approve it.`);closeModal()}
function login(){showModal(`<span class="eyebrow">AMG PORTAL</span><h2>Sign in to AMG Foundation</h2><p>Choose a role to preview the experience. Real authentication will use Supabase Auth.</p><form class="form" id="loginForm"><select id="loginRole"><option value="learner">🎓 Learner</option><option value="librarian">📚 Librarian</option><option value="teacher">👩‍🏫 Teacher</option><option value="parent">👪 Parent</option><option value="admin">🛡️ Admin</option></select><input type="email" placeholder="Email address" required><input type="password" placeholder="Password" required><button class="btn btn-primary">Continue</button></form>`);$('#loginForm').onsubmit=e=>{e.preventDefault();openPortal($('#loginRole').value)}}
function openPortal(role){const names={admin:'Admin Control Centre',librarian:'Librarian Dashboard',teacher:'Teacher Portal',learner:'Learner Dashboard',parent:'Parent Portal'};const data={admin:[['Users & roles','Manage administrators, librarians, teachers, learners and parents.'],['System settings','Library policies, opening hours, notifications and configuration.'],['Reports','Usage, borrowing, resources, fines and impact reporting.'],['Security','Role-based permissions and audit logs.']],librarian:[['Inventory','Add/edit books, copies, covers, PDFs, categories and shelf locations.'],['Borrowing','Issue, return, renew, reserve and track due dates.'],['Overdue & fines','See overdue learners and record configurable fines.'],['Analytics','Most borrowed books, active readers and popular subjects.']],teacher:[['Resources','Upload notes, revision materials and legally shareable PDFs.'],['Quizzes','Create quizzes, explanations and learner challenges.'],['Recommendations','Recommend books/resources to classes or learners.'],['Progress','Review learning activity where permitted.']],learner:[['My books','Borrowed, reserved, saved and reading-history records.'],['Learning','Notes, past papers, quizzes and study tools.'],['Achievements','XP, badges, reading streaks and challenges.'],['Study planner','Exam countdowns, Pomodoro sessions and personal notes.']],parent:[['Child activity','Borrowed books, due dates and reading activity.'],['Learning progress','Quiz results and learning-resource activity where enabled.'],['Notifications','Due-date and library updates.'],['Support','Contact the library and view community announcements.']]};showModal(`<div class="portal-head"><div><span class="eyebrow">${role.toUpperCase()} PORTAL</span><h2>${names[role]}</h2></div><button class="btn btn-ghost" onclick="closeModal()">Close</button></div><div class="portal-grid">${data[role].map(x=>`<div class="portal-card"><h4>${x[0]}</h4><p>${x[1]}</p></div>`).join('')}</div>${role==='librarian'?`<div style="margin-top:20px"><h3>Inventory snapshot</h3><div class="table-wrap"><table class="mini-table"><tr><th>Book</th><th>Status</th><th>Copies</th><th>Action</th></tr>${books.slice(0,5).map(b=>`<tr><td>${b.title}</td><td>${b.status}</td><td>${b.available}/${b.copies}</td><td><button class="text-btn" onclick="showBook(${b.id})">View</button></td></tr>`).join('')}</table></div><button class="btn btn-primary" style="margin-top:15px" onclick="openAddBook()">+ Add book</button></div>`:''}${role==='learner'?`<div class="portal-card" style="margin-top:15px"><h4>Reading streak 🔥</h4><p>7 days · 1,240 XP · 10 books challenge in progress.</p></div>`:''}`)}
function openAddBook(){showModal(`<span class="eyebrow">INVENTORY</span><h2>Add a book</h2><form class="form" id="addBook"><input id="bt" placeholder="Title" required><input id="ba" placeholder="Author" required><select id="bc"><option>Academic</option><option>Fiction</option><option>Technology</option><option>Personal Growth</option><option>Children</option></select><input id="bs" placeholder="Shelf / location" value="A-01" required><input id="bn" type="number" min="1" value="1" placeholder="Copies" required><button class="btn btn-primary">Add to catalogue</button></form>`);$('#addBook').onsubmit=e=>{e.preventDefault();const n=Number($('#bn').value);books=getBooks();books.push({id:Date.now(),title:$('#bt').value,author:$('#ba').value,cat:$('#bc').value,status:'Available',shelf:$('#bs').value,copies:n,available:n,resource:'Book'});saveBooks(books);render($('#searchInput').value);alert('Book added to the local demo catalogue.');closeModal()}}
function openQuiz(){showModal(`<span class="eyebrow">QUICK QUIZ</span><h2>Physics Challenge</h2><p>Which unit is used to measure electric current?</p><div class="form"><button class="btn btn-primary" onclick="quizAnswer(false)">Volt</button><button class="btn btn-primary" onclick="quizAnswer(true)">Ampere</button><button class="btn btn-ghost" onclick="quizAnswer(false)">Ohm</button></div>`)}
function quizAnswer(correct){alert(correct?'Correct! Ampere is the SI unit of electric current. 🎉':'Not quite. Review the topic and try again.');closeModal()}
function openTimer(){let seconds=1500,interval;showModal(`<span class="eyebrow">STUDY TOOL</span><h2>Pomodoro Focus Timer</h2><div class="timer" id="timer">25:00</div><div class="timer-actions"><button class="btn btn-primary" id="startTimer">Start</button><button class="btn btn-ghost" id="resetTimer">Reset</button></div><p style="text-align:center;color:#6e7773">25 minutes focus · 5 minutes break</p>`);$('#startTimer').onclick=()=>{clearInterval(interval);interval=setInterval(()=>{if(seconds<=0){clearInterval(interval);alert('Focus session complete! Take a 5-minute break.');return}seconds--;$('#timer').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`},1000)};$('#resetTimer').onclick=()=>{clearInterval(interval);seconds=1500;$('#timer').textContent='25:00'}}
function openAI(){showModal(`<span class="eyebrow">AI LEARNING ASSISTANT</span><h2>Ask and learn.</h2><p>The production version will connect to an AI API and optionally ground answers in approved library resources.</p><div class="ai-chat">Try: “Explain photosynthesis in a simple way.”<br>“Give me five quadratic-equation practice questions.”</div><form class="form" id="aiForm"><input id="aiInput" placeholder="Ask a learning question..." required><button class="btn btn-primary">Ask assistant</button></form>`);$('#aiForm').onsubmit=e=>{e.preventDefault();alert('AI connection is ready for the backend phase. Your question was: '+$('#aiInput').value)}}
$$('.category').forEach(b=>b.onclick=()=>{$$('.category').forEach(x=>x.classList.remove('active'));b.classList.add('active');current=b.dataset.category;render($('#searchInput').value)});
$('#searchInput').addEventListener('input',e=>render(e.target.value));$('#searchBtn').onclick=()=>render($('#searchInput').value);$$('[data-query]').forEach(b=>b.onclick=()=>{$('#searchInput').value=b.dataset.query;render(b.dataset.query);$('#books').scrollIntoView({behavior:'smooth'})});$('#viewAllBtn').onclick=()=>{current='All';$$('.category').forEach(x=>x.classList.toggle('active',x.dataset.category==='All'));$('#searchInput').value='';render()};
$('#loginBtn').onclick=login;$('#mobileLogin').onclick=login;$('#joinBtn').onclick=login;$('#menuBtn').onclick=()=>$('#mobileMenu').classList.toggle('open');$('#modalClose').onclick=closeModal;$('.modal-backdrop').onclick=closeModal;$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('amg-dark',document.body.classList.contains('dark')?'1':'0');$('#themeBtn').textContent=document.body.classList.contains('dark')?'☀':'☾'};if(localStorage.getItem('amg-dark')==='1'){document.body.classList.add('dark');$('#themeBtn').textContent='☀'}
$('.open-quiz').onclick=openQuiz;$('#timerBtn').onclick=openTimer;$('.open-ai').onclick=openAI;$$('[data-role]').forEach(b=>b.onclick=()=>openPortal(b.dataset.role));$$('[data-resource]').forEach(b=>b.onclick=()=>showModal(`<span class="eyebrow">LEARNING CENTRE</span><h2>${b.dataset.resource==='notes'?'Notes, Past Papers & Resources':'Digital Reading Room'}</h2><p>Resources will be organized by subject, form, topic, type and year. Digital books will only be provided where AMG has permission to share them.</p><div class="portal-grid"><div class="portal-card"><h4>Mathematics</h4><p>Notes · KCSE · Revision · Quizzes</p></div><div class="portal-card"><h4>Biology</h4><p>Notes · KCSE · Topic practice</p></div><div class="portal-card"><h4>Physics</h4><p>Electricity · Mechanics · Practice</p></div><div class="portal-card"><h4>English & Kiswahili</h4><p>Language · Literature · Revision</p></div></div>`));window.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});render();