'use client';
import Link from 'next/link';
import { ArrowRight, BookOpen, Brain, Clock3, Library, Search, UserRound } from 'lucide-react';

const books=[['Biology Today','Form 3 • Biology'],['Essential Mathematics','Form 3 • Mathematics'],['Physics for Schools','Form 2 • Physics']];
export default function Home(){return <main className="min-h-screen bg-slate-50 text-slate-900"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-5"><Link href="/" className="flex items-center gap-3 font-black"><span className="rounded-xl bg-blue-600 p-2 text-white"><BookOpen/></span><span>AMG FOUNDATION <span className="hidden text-slate-400 sm:inline">Community Library</span></span></Link><nav className="hidden items-center gap-7 text-sm font-semibold md:flex"><a href="#library">Library</a><a href="#learning">Learning</a><a href="#about">About</a></nav><Link href="/learner/login" className="flex items-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-bold"><UserRound size={17}/> Member Sign In</Link></div></header>
<section className="mx-auto max-w-7xl px-5 pb-20 pt-20"><div className="max-w-3xl"><span className="rounded-full bg-blue-100 px-4 py-2 text-xs font-black tracking-wide text-blue-700">OPEN TO EVERY LEARNER • NO LOGIN REQUIRED</span><h1 className="mt-7 text-5xl font-black tracking-tight md:text-7xl">Read. Learn. <span className="text-blue-600">Grow.</span></h1><p className="mt-6 text-lg leading-8 text-slate-600">Welcome to AMG FOUNDATION Community Library. Explore books, learning resources, quizzes and study tools freely. Become a member only when you are ready to borrow and track your library activity.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#library" className="rounded-xl bg-blue-600 px-6 py-3 font-bold text-white">Explore Library</a><a href="#learning" className="rounded-xl border bg-white px-6 py-3 font-bold">Start Learning</a></div></div><div className="mt-12 grid gap-4 sm:grid-cols-3"><Quick icon={<Library/>} title="Browse freely" text="Search the catalogue without an account."/><Quick icon={<Brain/>} title="Learn freely" text="Use public notes, quizzes and study tools."/><Quick icon={<Clock3/>} title="Become a member" text="Register with the librarian when you want library membership."/></div></section>
<section id="library" className="border-y bg-white px-5 py-16"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="font-bold text-blue-600">LIBRARY CATALOGUE</p><h2 className="mt-2 text-3xl font-black">Discover something to read</h2></div><div className="flex items-center gap-2 rounded-xl border px-4 py-3 text-sm text-slate-400"><Search size={18}/> Search books, subjects or authors</div></div><div className="mt-8 grid gap-5 md:grid-cols-3">{books.map(([title,meta])=><article key={title} className="rounded-2xl border p-6 shadow-sm"><div className="grid h-40 place-items-center rounded-xl bg-slate-100 text-blue-600"><BookOpen size={45}/></div><h3 className="mt-5 text-lg font-black">{title}</h3><p className="mt-1 text-sm text-slate-500">{meta}</p><button className="mt-5 flex items-center gap-2 font-bold text-blue-600">View book <ArrowRight size={16}/></button></article>)}</div></div></section>
<section id="learning" className="mx-auto max-w-7xl px-5 py-16"><p className="font-bold text-blue-600">LEARNING CENTRE</p><h2 className="mt-2 text-3xl font-black">Learning is open to everyone.</h2><div className="mt-7 grid gap-5 md:grid-cols-3"><Quick icon={<Brain/>} title="Notes & Past Papers" text="Explore structured study resources by subject and form."/><Quick icon={<Clock3/>} title="Study Tools" text="Use Pomodoro, flashcards and reading tools."/><Quick icon={<BookOpen/>} title="Interactive Quizzes" text="Test your knowledge and learn from explanations."/></div></section>
<section id="about" className="bg-slate-950 px-5 py-16 text-white"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 md:flex-row md:items-center"><div><p className="text-sm font-bold text-blue-300">LIBRARY MEMBERSHIP</p><h2 className="mt-2 text-3xl font-black">Want to borrow books?</h2><p className="mt-3 max-w-xl text-slate-400">You don't need an account to browse or learn. Visit the librarian and they will register you as an AMG member when you want to borrow or track your library activity.</p></div><div className="flex flex-wrap gap-3"><Link href="/learner/register" className="rounded-xl bg-blue-600 px-6 py-3 font-bold">Become a Member</Link><Link href="/librarian/login" className="rounded-xl border border-slate-700 px-6 py-3 font-bold">Librarian Desk</Link></div></div></section><footer className="bg-slate-950 px-5 pb-8 text-center text-sm text-slate-500">© 2026 AMG FOUNDATION Community Library</footer></main>}
function Quick({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <article className="rounded-2xl border bg-white p-6 shadow-sm"><div className="w-fit rounded-xl bg-blue-50 p-3 text-blue-600">{icon}</div><h3 className="mt-4 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></article>}
